PREFIXES = ['Sir',
            'Queen',
            'Professor',
            'Princess',
            'Prince',
            "Ol'",
            'Mrs.',
            'Mr.',
            'Madam',
            'Lord',
            "Lil' Miss",
            'Lady',
            'King',
            'Dr.',
            'Chairwoman',
            'Chairman']

SUFFIXES = ['v3',
            'v2',
            'the Third',
            'the Second',
            'the Fourth',
            'the First',
            'mk IV',
            'Ph.D.',
            'Esq.']

LASTNAMES= ['Zimmerman',
            'Winters',
            'Williams',
            'White',
            'Wang',
            'Wagner',
            'Tyson',
            'Thompson',
            'Tanaka',
            'Suzuki',
            'Summers',
            'Smith',
            'Sherwin',
            'Schmidt',
            'Sawyer',
            'Santos',
            'Roy',
            'Rodriguez',
            'Robertson',
            'Popov',
            'Pinkman',
            'Pickles',
            'Perez',
            'Papageorgio',
            'Otto',
            'Nakamura',
            'Nakamoto',
            'Murphy',
            'Muncher',
            'Miller',
            'McKenzie',
            'McIver',
            'McGee',
            'Martinez',
            'Martin',
            'Magoo',
            'Magillicutty',
            'Magee',
            'MacInnis',
            'MacDonald',
            'Lund',
            'Lopez',
            'Lee',
            'Leblanc',
            'Lardhi',
            'Kozlov',
            'Kozak',
            'Klein',
            'Jones',
            'Johnson',
            'Jefferson',
            'Jameal',
            'Jackson',
            'Ivanov',
            'Idol',
            'Howard',
            'Hardy',
            'Gomez',
            'Gallagher',
            'Fischer',
            'Fernandez',
            'Federov',
            'Edwards',
            'DuPont',
            'Doolittle',
            'Denver',
            'DeJardan',
            'Davis',
            'Cooper',
            'Clark',
            'Chen',
            'Catman',
            'Cat',
            'Castro',
            'Campbell',
            'Callahan',
            'Boutlier',
            'Black',
            'Bigglesworth',
            'Berger',
            'Ball',
            'Baldwin',
            'Alvarez',
            'Adams',
            'Abawi']

FIRSTNAMES = ['Zoe',
            'Ziggy',
            'Wojack',
            'Winston',
            'Willow',
            'Weezey',
            'Wanda',
            'Wallace',
            'Victor',
            'Tony',
            'Tommy',
            'Timmy',
            'Tigger',
            'Thor',
            'Theodore',
            'Thanos',
            'Teddy',
            'Tabby',
            'Sylvester',
            'Stephan',
            'Stella',
            'Sprinkles',
            'Sophie',
            'Solomon',
            'Sofia',
            'Snowball',
            'Smokey',
            'Skittles',
            'Simon',
            'Simba',
            'Shadow',
            'Sasha',
            'Sapphire',
            'Sam',
            'Sally',
            'Sadie',
            'Rosey',
            'Rosanne',
            'Ronny',
            'Ricardo',
            'Raven',
            'Rachelle',
            'Queenie',
            'Pretty',
            'Poppy',
            'Pippa',
            'Pierre',
            'Petey',
            'Penny',
            'Penelope',
            'Pearl',
            'Peanut',
            'Patrick',
            'Paris',
            'Pamela',
            'Oreo',
            'Olivia',
            'Oliver',
            'Nugget',
            'Nora',
            'Noodle',
            'Nala',
            'Molly',
            'Misty',
            'Milton',
            'Midnight',
            'Mia',
            'Mellow',
            'Maximus',
            'Marshmallow',
            'Maria',
            'Manuel',
            'Luna',
            'Lulu',
            'Lucy',
            'Lucille',
            'Lou',
            'Lolo',
            'Lola',
            'Loki',
            'Lilly',
            'Lightning',
            'Leonard',
            'Layla',
            'Laurielle',
            'Larry',
            'Kimmy',
            'Kiki',
            'Kassy',
            'Juno',
            'Julie',
            'Joy',
            'Joey',
            'Joe',
            'Jimbo',
            'Jesse',
            'Jellybean',
            'Jasmine',
            'James',
            'Isra',
            'Isis',
            'Hillary',
            'Hercules',
            'Gregory',
            'Gizzabelle',
            'Gizmo',
            'Ginger',
            'Germaine',
            'Georgie',
            'Garfield',
            'Fluffy',
            'Fiona',
            'Figaro',
            'Fernando',
            'Felix',
            'Farrah',
            'Eva',
            'Ethel',
            'Ernie',
            'Emma',
            'Emery',
            'Ellie',
            'Elizabeth',
            'Egor',
            'Edson',
            'Edna',
            'Duchess',
            'Dolph',
            'Dimitri',
            'Diego',
            'Della',
            'Deezy',
            'Dante',
            'Damion',
            'Daisy',
            'Cynthia',
            'Cutie Pie',
            'Cola',
            'Coco',
            'Clifford',
            'Cleo',
            'Cinnamon',
            'Chloe',
            'Cheshire',
            'Charles',
            'Catman',
            'Casey',
            'Carlos',
            'Candy',
            'Cali',
            'Caesar',
            'Buzz',
            'Boots',
            'Boo',
            'Blaze',
            'Biscuit',
            'Bingo',
            'Bigglesworth',
            'Bert',
            'Bernard',
            'Benji',
            'Bella',
            'Beatrix',
            'Ava',
            'Autumn',
            'Austin',
            'Augustine',
            'Athena',
            'Asia',
            'Ashley',
            'Ariel',
            'Archie',
            'Amelia',
            'Amber',
            'Alex',
            'Albert',
            'Alan',
            'Adam',
            'Ada',
            'Abby']

def name_has_prefix(name):
    for prefix in PREFIXES:
        if f""" {prefix} """ in f""" {name} """:
            return prefix
    return None


def name_has_firstname(name):
    for firstname in FIRSTNAMES:
        if f""" {firstname} """ in f""" {name} """:
            return firstname
    return None


def name_has_lastname(name):
    for lastname in LASTNAMES:
        if f""" {lastname} """ in f""" {name} """:
            return lastname
    return None


def name_has_suffix(name):
    for suffix in SUFFIXES:
        if f""" {suffix} """ in f""" {name} """:
            return suffix
    return None
